### get all cards
GET http://localhost:8080/cards
# GET https://cse341-project1-jojo.onrender.com/cards


### get card by collection and id
GET http://localhost:8080/cards/action/651494f7921a031b2c4d931e
# GET https://cse341-project1-jojo.onrender.com/cards/action/650733317a9fdff3bcecfe43

### create action card
POST http://localhost:8080/cards/action/ HTTP/1.1
# POST https://cse341-project1-jojo.onrender.com/cards/action HTTP/1.1
content-type: application/json

{
  "name": "cellar",
  "cost": 2,
  "type": ["action"],
  "quantity": 10,
  "image": "/src/images/cellar.webp"
}

### create victory card
POST http://localhost:8080/cards/victory HTTP/1.1
# POST https://cse341-project1-jojo.onrender.com/cards/victory HTTP/1.1
content-type: application/json

{
  "name": "Estate",
  "cost": 2,
  "type": "victory",
  "value": "1",
  "quantity": "24",
  "image": "/src/images/estate.webp"
}

### put victory card
PUT http://localhost:8080/cards/victory/651e21d43caae2d179966161 HTTP/1.1
# PUT https://cse341-project1-jojo.onrender.com/cards/650733317a9fdff3bcecfe43 HTTP/1.1
content-type: application/json

{
  "name": "Estate",
  "cost": 2,
  "type": "victory",
  "value": "1",
  "quantity": "24",
  "image": "/src/images/estate.webp"
}

### put action card
PUT http://localhost:8080/cards/victory/651e56f012f673963bc8244e HTTP/1.1
# PUT https://cse341-project1-jojo.onrender.com/cards/650733317a9fdff3bcecfe43 HTTP/1.1
content-type: application/json

{
  "name": "Estate",
  "cost": 2,
  "type": "ho dee hoooo",
  "value": 1,
  "quantity": 24,
  "image": "/src/images/estate.webp"
}

### delete victory card
DELETE http://localhost:8080/cards/victory/651e58311a4efd9b1f06cca2 HTTP/1.1
# DELETE https://cse341-project1-jojo.onrender.com/cards/6511fc82bfdc1b4eb662f20c HTTP/1.1

### delete action card
DELETE http://localhost:8080/cards/action/651e21ab3caae2d179966160 HTTP/1.1
# DELETE https://cse341-project1-jojo.onrender.com/cards/6511fc82bfdc1b4eb662f20c HTTP/1.1